import type { Metadata } from "next";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import { FaLinkedin } from "react-icons/fa";
import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from "react-toastify";
import Sidebar from "@/components/SideBar";
import NavBar from "@/components/topBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`bg-white antialiased`}>
        {/* Sidebar and Main Content */}
        <NavBar />
        <div className="flex pt-16">
          <Sidebar />
          <main className="ml-32 flex-1 p-4">{children}</main>
        </div>

        <ToastContainer />

        {/* Footer */}
        <footer className="bg-gray-800 text-gray-300 ml-32 flex-1 p-4">
          <div className="container mx-auto flex flex-col md:flex-row justify-between items-center px-4">
            <p className="text-sm">
              &copy; {new Date().getFullYear()} Abdul. All rights reserved.
            </p>
            <div className="flex space-x-6">
              <a
                href="https://linkedin.com/in/abdul-hannan-a34a4922a"
                target="_blank"
                rel="noopener noreferrer"
                className="hover:text-white transition-colors duration-300"
              >
                <FaLinkedin size={24} />
              </a>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
